version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goods_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
    restart: unless-stopped
  
  app:
    build: .
    container_name: goods-app
    environment:
      DB_URL: "jdbc:mysql://mysql:3306/goods_db?useSSL=false&allowPublicKeyRetrieval=true"
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    links:
      - mysql

volumes:
  mysql-data:
